# Generated by Django 5.2.3 on 2025-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraitSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('trait', models.CharField(max_length=100)),
                ('days_after_planting', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
