# Generated by Django 5.2.3 on 2025-07-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germplasmDbId', models.CharField(max_length=50, unique=True)),
                ('germplasmName', models.CharField(max_length=100)),
                ('commonCropName', models.CharField(blank=True, max_length=50)),
                ('genus', models.CharField(blank=True, max_length=50)),
                ('species', models.CharField(blank=True, max_length=50)),
                ('pedigree', models.TextField(blank=True)),
                ('seedSource', models.CharField(blank=True, max_length=100)),
                ('synonyms', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageFile', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100, unique=True)),
                ('level_order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('className', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orcid', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100, unique=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programDbId', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleDbId', models.CharField(max_length=100, unique=True)),
                ('sampleName', models.CharField(max_length=255)),
                ('studyDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('observationUnitDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('germplasmDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('sampleType', models.CharField(default='Tissue', max_length=100)),
                ('takenBy', models.CharField(blank=True, max_length=100, null=True)),
                ('sampleTimestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonDbId', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TraitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('trait', models.CharField(max_length=100)),
                ('days_after_planting', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialDbId', models.CharField(max_length=100, unique=True)),
                ('trialName', models.CharField(max_length=255)),
                ('programName', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('additionalInfo', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantTraitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50)),
                ('trait', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraitTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100)),
                ('trait', models.CharField(max_length=100)),
                ('min_days_after_planting', models.PositiveIntegerField(blank=True, null=True)),
                ('max_days_after_planting', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status_flag', models.CharField(choices=[('🕓', 'Too Early'), ('⏳', 'Due Soon'), ('❌', 'Overdue'), ('✔️', 'Completed')], default='🕓', max_length=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='too-early', max_length=20)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trial')),
            ],
        ),
    ]
