# Generated by Django 5.2.3 on 2025-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_planttraitdata_status_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('class_field', models.CharField(blank=True, max_length=100)),
                ('scale', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
