# Generated by Django 5.2.3 on 2025-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_planttraitdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('due-soon', 'Due Soon'), ('overdue', 'Overdue'), ('too-early', 'Too Early')], default='too-early', max_length=50)),
            ],
        ),
    ]
