# Generated by Django 5.2.3 on 2025-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_fieldplot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldplot',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldplot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldplot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldplot',
            name='plant_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldplot',
            name='status',
            field=models.CharField(default='too-early', max_length=20),
        ),
    ]
