# Generated by Django 5.2.3 on 2025-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_fieldplot_planting_date_alter_fieldplot_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=100, unique=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
