# Generated by Django 5.2.3 on 2025-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_fieldplot_id_alter_plantdata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traittimeline',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traittimeline',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='traittimeline',
            unique_together={('plant_id', 'trait')},
        ),
    ]
