# Generated by Django 5.2.3 on 2025-07-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_trial_alter_fieldplot_id_alter_plantdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germplasmDbId', models.CharField(max_length=50, unique=True)),
                ('germplasmName', models.CharField(max_length=100)),
                ('commonCropName', models.CharField(blank=True, max_length=50)),
                ('genus', models.CharField(blank=True, max_length=50)),
                ('species', models.CharField(blank=True, max_length=50)),
                ('pedigree', models.TextField(blank=True)),
                ('seedSource', models.CharField(blank=True, max_length=100)),
                ('synonyms', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
