# Generated by Django 5.2.3 on 2025-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_trial_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldplot',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
