# Generated by Django 5.2.3 on 2025-07-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_fieldplot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldplot',
            name='trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trial'),
        ),
    ]
