# Generated by Django 5.2.3 on 2025-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_fieldplot_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programDbId', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
