# Generated by Django 5.2.3 on 2025-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleDbId', models.CharField(max_length=100, unique=True)),
                ('sampleName', models.CharField(max_length=255)),
                ('studyDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('observationUnitDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('germplasmDbId', models.CharField(blank=True, max_length=100, null=True)),
                ('sampleType', models.CharField(default='Tissue', max_length=100)),
                ('takenBy', models.CharField(blank=True, max_length=100, null=True)),
                ('sampleTimestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonDbId', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
