# Generated by Django 5.2.3 on 2025-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_sample_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageFile', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationLevel', models.CharField(max_length=100, unique=True)),
                ('levelName', models.CharField(blank=True, max_length=100)),
                ('levelOrder', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('className', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orcid', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
